import {
  Brain,
  Megaphone,
  Target,
  Shield,
  Users,
  DollarSign,
  LineChart,
  Calendar,
  Scale,
  FlaskConical,
  Sparkles,
  ShoppingBag,
  HeartPulse,
  Compass,
  Handshake,
  Boxes,
  FileText,
} from "lucide-react";

export const AGENT_TABS = ["overview", "chat", "tools", "integrations", "ops", "dashboard", "workflows", "functions"];

export const AGENTS = [
  {
    id: "nexus",
    name: "Nexus",
    role: "Central Orchestrator",
    tagline: "Central orchestrator for cross-agent intelligence and workflows.",
    icon: Brain,
    color: "text-blue-600",
    capabilities: [
      "Intent recognition and routing",
      "Cross-agent workflow orchestration",
      "Conflict mediation and tradeoff analysis",
      "Business health scoring",
      "Cross-agent causal insights",
      "Strategic recommendations",
      "Alert correlation",
      "Autonomous workflow initiation",
    ],
    prompts: [
      "Give me today's executive briefing with top risks and opportunities.",
      "Route a product launch workflow across the right agents.",
      "Show cross-agent causes behind lead conversion changes.",
    ],
    functionName: "commandCenterIntelligence",
  },
  {
    id: "maestro",
    name: "Maestro",
    role: "Marketing and Lifecycle",
    tagline: "Full-stack marketing powerhouse for strategy, content, campaigns, ads, personalization, and analytics.",
    icon: Megaphone,
    color: "text-violet-600",
    capabilities: [
      "Market and competitor analysis",
      "Trend forecasting and viral prediction",
      "Audience segmentation and persona design",
      "Campaign orchestration across channels",
      "Copy generation for social, ads, and email",
      "Video/reel concept generation",
      "Social scheduling and unified inbox operations",
      "Email flow automation and A/B testing",
      "Ad budget allocation and bidding guidance",
      "Dynamic creative optimization",
      "Personalization and lifecycle targeting",
      "Marketing analytics and attribution",
      "Sentiment analysis and community intelligence",
      "Brand voice and compliance checks",
      "Influencer and affiliate collaboration workflows",
      "Cross-agent marketing coordination",
    ],
    prompts: [
      "Create a 90-day multi-channel growth plan with KPI targets and budget allocation.",
      "Generate a full launch campaign with social, email, and paid media assets.",
      "Analyze last month performance and tell me exactly what to change next week."
    ],
    functionName: "maestroSocialOps",
  },
  {
    id: "prospect",
    name: "Prospect",
    role: "Lead Generation",
    tagline: "Full-stack sales and acquisition engine for lead discovery, outreach, and pipeline intelligence.",
    icon: Target,
    color: "text-cyan-600",
    capabilities: [
      "Multi-source lead discovery and intent mining",
      "Lead enrichment and contact verification",
      "Predictive lead/account scoring",
      "Buying signal detection and prioritization",
      "Hyper-personalized outreach sequencing",
      "AI-assisted call qualification and objection handling",
      "ABM account mapping and committee intelligence",
      "Pipeline velocity and forecast intelligence",
      "Sales asset repository and template management",
      "Cross-agent lead handoff and revenue alignment",
    ],
    prompts: [
      "Find and rank 50 ICP-fit leads with buying signals from the last 30 days.",
      "Build a 5-step multi-channel sequence for enterprise prospects and schedule follow-ups.",
      "Show pipeline forecast, stage risks, and next best actions."
    ],
    functionName: "prospectLeadGeneration",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    role: "Security",
    tagline: "Full-stack security and privacy engine for threat intelligence, response automation, and compliance.",
    icon: Shield,
    color: "text-red-600",
    capabilities: [
      "Continuous threat intelligence and proactive hunting",
      "Zero-trust verification and access anomaly detection",
      "Autonomous incident detection and response",
      "Data protection and privacy engineering",
      "Cloud and SaaS security posture management",
      "Insider threat detection and case management",
      "Compliance evidence and audit automation",
      "Security library and cross-agent sharing",
    ],
    prompts: [
      "Show current security posture, active incidents, and top remediation actions.",
      "Generate a full incident report from last critical event and save to library.",
      "Run cloud posture and compliance checks and prioritize fixes."
    ],
    functionName: "sentinelSecurityMonitoring",
  },
  {
    id: "support-sage",
    name: "Support Sage",
    role: "Customer Support",
    tagline: "Omnichannel autonomous support engine with resolution workflows and a central Knowledge Base.",
    icon: Users,
    color: "text-emerald-600",
    capabilities: [
      "Omnichannel ticket intake and deduplication",
      "Smart triage and prioritization with sentiment/context",
      "Autonomous resolution with policy-aware actions",
      "Human handoff with full conversation context",
      "Refund/credit operations within compliance guardrails",
      "Knowledge Base authoring, versioning, and publishing",
      "CSAT/NPS and root-cause analytics",
      "Incident escalation and mass customer communications",
      "Cross-agent feedback routing (product, marketing, finance)",
      "Support forecasting and performance intelligence",
    ],
    prompts: [
      "Show all high-priority open tickets and recommend immediate actions.",
      "Resolve this billing issue and draft customer response + KB article.",
      "Analyze this week’s support drivers and propose prevention workflows."
    ],
    functionName: "supportSageCustomerService",
  },
  {
    id: "centsible",
    name: "Centsible",
    role: "Finance",
    tagline: "Full-stack finance and revenue engine for FP&A, treasury, optimization, compliance, and stakeholder reporting.",
    icon: DollarSign,
    color: "text-green-600",
    capabilities: [
      "Strategic financial planning and multi-scenario forecasting",
      "Real-time cash flow and treasury optimization",
      "Revenue intelligence, recognition, and leakage prevention",
      "Cost control, procurement intelligence, and spend governance",
      "Core accounting automation and audit-ready reporting",
      "Financial risk, fraud monitoring, and compliance controls",
      "Board and investor communication automation",
      "Documents library with cross-agent financial sharing",
    ],
    prompts: [
      "Forecast cash flow for the next 6 months and flag liquidity risks.",
      "Generate a board-ready financial deck with last quarter highlights.",
      "Show top profitability drivers and recommend budget reallocation."
    ],
    functionName: "centsibleFinanceEngine",
  },
  {
    id: "sage",
    name: "Sage",
    role: "Strategy",
    tagline: "Full-stack growth strategy engine for market intelligence, modeling, OKRs, and strategic execution.",
    icon: LineChart,
    color: "text-amber-600",
    capabilities: [
      "Strategic intelligence and market sensing",
      "Opportunity identification and white-space analysis",
      "Financial modeling and scenario simulation",
      "OKR generation and cascade planning",
      "Strategic risk register and resilience planning",
      "Initiative prioritization and portfolio optimization",
      "Board-ready strategy communication",
      "Strategy library and cross-agent sharing",
    ],
    prompts: [
      "Create a strategic growth plan for the next 12 months with quantified scenarios.",
      "Model the impact of pricing, expansion, and retention moves on revenue and risk.",
      "Generate board-ready strategy update with top opportunities and mitigations."
    ],
    functionName: "sageBussinessStrategy",
  },
  {
    id: "chronos",
    name: "Chronos",
    role: "Scheduling",
    tagline: "Full-stack scheduling and time intelligence engine for meetings, focus time, and organizational time ROI.",
    icon: Calendar,
    color: "text-sky-600",
    capabilities: [
      "Organizational time intelligence and audits",
      "Intelligent meeting orchestration and optimization",
      "Agenda generation and follow-through automation",
      "Deep work protection and interruption control",
      "Global timezone-aware fair scheduling",
      "Resource and logistics booking support",
      "Time analytics and productivity forecasting",
      "Schedule library templates and policy management",
    ],
    prompts: [
      "Schedule a cross-functional meeting with optimal attendance and agenda.",
      "Run a time audit for this team and recommend meeting policy fixes.",
      "Create recurring deep-work protection policy and save it to the library."
    ],
    functionName: "chronosSchedulingEngine",
  },
  {
    id: "veritas",
    name: "Veritas",
    role: "Legal and Compliance",
    tagline: "Full-stack legal and compliance engine for regulatory intelligence, contracts, privacy, governance, and risk operations.",
    icon: Scale,
    color: "text-indigo-600",
    capabilities: [
      "Regulatory monitoring and impact analysis across jurisdictions",
      "Contract lifecycle automation with risk scoring and redlining",
      "Data privacy and data-subject-rights operations",
      "IP portfolio management and open-source compliance",
      "Litigation, legal holds, and e-discovery support",
      "Corporate governance and entity management",
      "Employment law and labor compliance workflows",
      "Legal library with contracts, clauses, evidence, and risk registers",
    ],
    prompts: [
      "Review this vendor contract and highlight key legal and compliance risks.",
      "Show contracts expiring next quarter with renewal recommendations.",
      "Prepare a legal risk assessment for entering the EU market."
    ],
    functionName: "veritasComplianceValidation",
  },
  {
    id: "inspect",
    name: "Inspect",
    role: "Quality Assurance",
    tagline: "Full-stack quality and analytics engine for test automation, defect intelligence, and release governance.",
    icon: FlaskConical,
    color: "text-cyan-700",
    capabilities: [
      "Unified quality strategy, policy, and governance controls",
      "Autonomous test generation and orchestration across environments",
      "Content, creative, accessibility, and compliance QA",
      "Process quality monitoring and root-cause intelligence",
      "Physical product quality workflows and supplier QA",
      "Advanced defect prediction and anomaly analytics",
      "Release readiness scoring, gates, and post-release validation",
      "Quality library with test assets, defects, reports, and audit trails",
    ],
    prompts: [
      "Run a regression suite and generate release readiness score with blockers.",
      "Analyze critical defects and cluster likely root causes.",
      "Show quality coverage gaps and recommend priority test additions."
    ],
    functionName: "inspectQualityEngine",
  },
  {
    id: "canvas",
    name: "Canvas",
    role: "Creative",
    tagline: "Creative and brand production engine with an integrated Content Bank.",
    icon: Sparkles,
    color: "text-purple-600",
    capabilities: [
      "Brand identity creation and guideline management",
      "Text-to-image generation and advanced image editing",
      "Text-to-video and image-to-video production",
      "Motion graphics and auto-captioning workflows",
      "3D/AR concept generation and visualization support",
      "Graphic design for social, ads, decks, and print",
      "UI/UX mockup and design system support",
      "Creative strategy and moodboard ideation",
      "Creative operations and approval workflows",
      "Creative performance analytics and optimization",
      "Content Bank upload and asset organization",
      "Tagging, search, and version tracking",
      "Derivative generation from source assets",
      "Rights and license metadata tracking",
      "Share assets with Maestro and other agents",
      "Cross-agent creative delivery orchestration",
    ],
    prompts: [
      "Use my uploaded product video to generate 5 reels and matching thumbnails.",
      "Create a complete brand identity system and starter social kit.",
      "Audit current assets for brand consistency and suggest fixes."
    ],
    functionName: "canvasCreativeGeneration",
  },
  {
    id: "merchant",
    name: "Merchant",
    role: "Commerce",
    tagline: "Full-stack commerce engine for products, inventory, pricing, fulfillment, and revenue optimization.",
    icon: ShoppingBag,
    color: "text-emerald-700",
    capabilities: [
      "Product lifecycle management and catalog intelligence",
      "Predictive inventory and supply chain orchestration",
      "Dynamic pricing and promotion optimization",
      "Omnichannel selling and channel operations",
      "Personalized shopping and recommendation intelligence",
      "Order routing, fulfillment, and returns orchestration",
      "Loyalty, subscriptions, and customer lifetime value modeling",
      "Commerce analytics, profitability insights, and library management",
    ],
    prompts: [
      "Show top-selling products, inventory risks, and margin opportunities this week.",
      "Create a flash-sale plan for overstock SKUs and estimate revenue and margin impact.",
      "Optimize pricing for Product X against competitor moves and save the strategy to library."
    ],
    functionName: "merchantProductManagement",
  },
  {
    id: "pulse",
    name: "Pulse",
    role: "People and Culture",
    tagline: "Full-stack people and culture engine for hiring, performance, engagement, wellbeing, and policy operations.",
    icon: HeartPulse,
    color: "text-pink-600",
    capabilities: [
      "Talent intelligence, workforce planning, and succession analysis",
      "Recruiting automation from job description to offer operations",
      "Onboarding orchestration and early-tenure integration",
      "Performance management, development, and skill-gap analysis",
      "Engagement, burnout detection, and wellbeing interventions",
      "Compensation, benefits, payroll, and rewards intelligence",
      "Culture communications, policy operations, and compliance controls",
      "People library and cross-agent workforce collaboration",
    ],
    prompts: [
      "Show headcount, hiring pipeline, and retention risk hotspots by department.",
      "Create a Senior AI Engineer job description and sourcing strategy, then save it to library.",
      "Assess burnout risk for the product team and recommend interventions."
    ],
    functionName: "pulseHREngine",
  },
  {
    id: "compass",
    name: "Compass",
    role: "Market Intelligence",
    tagline: "Full-stack market intelligence engine for competitor tracking, trend detection, and strategic alerts.",
    icon: Compass,
    color: "text-teal-600",
    capabilities: [
      "Omnidirectional market sensing and event detection",
      "Competitor deep intelligence and profiling",
      "Predictive competitive intelligence and war-gaming",
      "Market and industry trend forecasting",
      "Customer sentiment and audience intelligence",
      "Early-warning strategic alerting",
      "Deep-dive market reports and battle cards",
      "Market library and cross-agent sharing",
    ],
    prompts: [
      "What are our competitors doing this week and what should we do next?",
      "Detect emerging trends in our market and rank opportunities by impact.",
      "Generate and store a battle card for our top competitor."
    ],
    functionName: "compassMarketIntelligence",
  },
  {
    id: "part",
    name: "Part",
    role: "Partnerships",
    tagline: "Full-stack partnerships engine for partner discovery, lifecycle management, co-selling, and alliance performance.",
    icon: Handshake,
    color: "text-blue-700",
    capabilities: [
      "Intelligent partner discovery and strategic fit scoring",
      "Autonomous partner outreach, qualification, and meeting orchestration",
      "Partner lifecycle operations with onboarding, tiering, and QBR automation",
      "Co-marketing and co-selling orchestration with deal registration",
      "Influencer and affiliate program management",
      "Strategic alliance and technology integration coordination",
      "Partner ROI, health scoring, and channel-conflict intelligence",
      "Partnership governance, compliance, and library management",
    ],
    prompts: [
      "Discover high-fit technology partners in AI analytics and rank them by strategic fit.",
      "Create a partner outreach sequence and schedule a QBR for our top reseller.",
      "Analyze partner ecosystem gaps and propose co-marketing opportunities."
    ],
    functionName: "partPartnershipEngine",
  },
  {
    id: "atlas",
    name: "Atlas",
    role: "Operations",
    tagline: "Full-stack operations engine for process orchestration, resource optimization, and workflow automation.",
    icon: Boxes,
    color: "text-orange-600",
    capabilities: [
      "Intelligent process discovery and workflow design",
      "Autonomous cross-agent workflow orchestration",
      "Resource orchestration and capacity planning",
      "Operational analytics and bottleneck detection",
      "End-to-end business process automation",
      "Continuous process improvement and SOP generation",
      "Project and portfolio orchestration",
      "Workflow library management and reuse",
    ],
    prompts: [
      "Design and launch a cross-team workflow for next month’s initiative.",
      "Analyze current operational bottlenecks and propose optimized flow.",
      "Create a reusable workflow template and SOP for onboarding."
    ],
    functionName: "atlasWorkflowAutomation",
  },
  {
    id: "scribe",
    name: "Scribe",
    role: "Knowledge",
    tagline: "Full-stack knowledge and documentation engine for capture, retrieval, decisions, and SOP intelligence.",
    icon: FileText,
    color: "text-slate-700",
    capabilities: [
      "Autonomous knowledge capture and ingestion",
      "Intelligent knowledge organization and graph linking",
      "Semantic retrieval and conversational Q&A",
      "Decision and rationale tracking",
      "Process documentation and SOP generation",
      "Collaborative knowledge building and curation",
      "Knowledge analytics and gap detection",
      "Knowledge library and cross-agent sharing",
    ],
    prompts: [
      "Find all decisions related to our expansion strategy and summarize rationale.",
      "Generate SOP from recent process logs and save to library.",
      "Run knowledge gap analysis and draft missing documentation."
    ],
    functionName: "scribeKnowledgeBase",
  },
];

export const AGENT_BY_ID = Object.fromEntries(AGENTS.map((a) => [a.id, a]));

export function normalizeAgentId(value = "") {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-");
}
