import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const payload = await req.json();
    const { product_ids, platform, campaign_theme } = payload;

    // Fetch products
    const products = await Promise.all(
      product_ids.map(id => base44.entities.Product.read(id))
    );

    // Filter products that are shoppable-enabled
    const shoppableProducts = products.filter(p => p.shoppable_enabled && p.status === 'active');

    if (shoppableProducts.length === 0) {
      return Response.json({
        status: 'error',
        message: 'No shoppable products found. Enable products for social commerce first.'
      }, { status: 400 });
    }

    // Generate post content with product placement
    const contentResponse = await base44.integrations.Core.InvokeLLM({
      prompt: `Create a shoppable social media post for ${platform}:

Products to feature:
${shoppableProducts.map(p => `- ${p.name}: $${p.price} - ${p.description}`).join('\n')}

Theme: ${campaign_theme || 'product showcase'}

Create:
1. Engaging caption (2-3 sentences) that naturally highlights the products
2. Call-to-action that encourages shopping
3. 3-5 relevant hashtags
4. Product placement suggestion (which products to feature prominently)

Make it feel organic, not salesy. Focus on lifestyle/benefits.`,
      response_json_schema: {
        type: 'object',
        properties: {
          caption: { type: 'string' },
          cta: { type: 'string' },
          hashtags: { type: 'array', items: { type: 'string' } },
          featured_products: { type: 'array', items: { type: 'string' } }
        }
      }
    });

    const { caption, cta, hashtags } = contentResponse;

    // Create SocialPost
    const socialPost = await base44.asServiceRole.entities.SocialPost.create({
      platform,
      caption: caption + '\n\n' + cta + '\n\n' + hashtags.join(' '),
      status: 'draft',
      format: 'image',
      scheduled_time: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // 48h from now
      tags: ['shoppable', 'commerce', ...hashtags]
    });

    // Create ShoppablePost linking products
    const shoppablePost = await base44.asServiceRole.entities.ShoppablePost.create({
      social_post_id: socialPost.id,
      platform,
      products_tagged: shoppableProducts.map(p => ({
        product_id: p.id,
        product_name: p.name,
        price: p.price
      })),
      status: 'draft',
      auto_generated: true,
      merchant_tracking_data: {
        utm_source: platform,
        utm_campaign: campaign_theme || 'social_commerce',
        tracking_pixel_fired: false
      }
    });

    // Create ContentAsset for visual
    const visualBrief = `Product showcase for ${platform}: ${shoppableProducts.map(p => p.name).join(', ')}. Style: lifestyle, bright, aspirational. Include all products in frame.`;
    
    await base44.asServiceRole.entities.ContentAsset.create({
      title: `${platform} Shoppable Post - ${shoppableProducts[0].name}`,
      type: 'social_image',
      content: visualBrief,
      status: 'pending_creation',
      tags: ['shoppable', platform, 'merchant'],
      notes: `Auto-generated by Merchant AI. Products: ${shoppableProducts.map(p => p.name).join(', ')}`
    });

    // Create Notification
    await base44.asServiceRole.entities.Notification.create({
      type: 'shoppable_post_ready',
      title: `🛍️ Shoppable Post Generated: ${platform}`,
      message: `Post created featuring ${shoppableProducts.length} products. Visual asset pending.`,
      priority: 'medium',
      action_url: `/SocialPost?id=${socialPost.id}`,
      recipient_role: 'admin'
    });

    return Response.json({
      status: 'success',
      social_post_id: socialPost.id,
      shoppable_post_id: shoppablePost.id,
      platform,
      products_featured: shoppableProducts.length,
      caption: caption + '\n\n' + cta
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});