import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const payload = await req.json();
    const { action, partner_id, participant_id } = payload;

    // action: 'score_partnership', 'nurture_sequence', 'tier_upgrade', 'commission_calculate'

    let result = null;

    if (action === 'score_partnership') {
      // Sage scores a partner's relationship strength and opportunity
      const partner = await base44.entities.Partner.read(partner_id);
      const enhancedData = await base44.asServiceRole.entities.ReferralPartnerEnhanced.list().then(
        data => data.find(d => d.partner_id === partner_id)
      );

      const scoringResponse = await base44.integrations.Core.InvokeLLM({
        prompt: `Score this referral partner's value:
Partner: ${partner.company_name}
Type: ${partner.type}
Sector: ${enhancedData?.sector}
Referrals in 90 days: ${enhancedData?.referrals_in_last_90_days}
Conversion rate: ${enhancedData?.conversion_rate}%
Current LTV: $${enhancedData?.current_ltv_from_partner}
Relationship strength: ${enhancedData?.relationship_score}%

Score 0-100 and recommend: tier level (bronze/silver/gold/platinum), commission rate, engagement frequency`,
        response_json_schema: {
          type: 'object',
          properties: {
            overall_score: { type: 'number' },
            recommended_tier: { type: 'string' },
            commission_rate: { type: 'number' },
            engagement_frequency: { type: 'string' },
            churn_risk: { type: 'number' }
          }
        }
      });

      // Update partner record
      await base44.asServiceRole.entities.ReferralPartnerEnhanced.update(enhancedData?.id, {
        relationship_score: scoringResponse.overall_score,
        relationship_tier: scoringResponse.recommended_tier,
        commission_rate_percent: scoringResponse.commission_rate,
        churn_risk_score: scoringResponse.churn_risk
      });

      result = scoringResponse;
    }

    if (action === 'nurture_sequence') {
      // Trigger personalized outreach sequence
      const partner = await base44.entities.Partner.read(partner_id);

      // Step 1: Send update email (generated by Marketing AI)
      const emailContent = await base44.integrations.Core.InvokeLLM({
        prompt: `Write a brief, professional email to ${partner.company_name} updating them on new services and partnership opportunities. Make it personal.`,
        response_json_schema: {
          type: 'object',
          properties: {
            subject: { type: 'string' },
            body: { type: 'string' }
          }
        }
      });

      // Send email
      await base44.integrations.Core.SendEmail({
        to: partner.contact_email,
        subject: emailContent.subject,
        body: emailContent.body
      });

      // Schedule follow-up
      await base44.asServiceRole.entities.Task.create({
        title: `Follow-up call: ${partner.company_name}`,
        description: 'Discuss partnership expansion',
        status: 'pending',
        due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
      });

      result = {
        action: 'nurture_sequence_triggered',
        email_sent: true,
        follow_up_scheduled: true
      };
    }

    if (action === 'tier_upgrade') {
      // Assess and potentially upgrade partner tier
      const enhanced = await base44.asServiceRole.entities.ReferralPartnerEnhanced.list().then(
        data => data.find(d => d.partner_id === partner_id)
      );

      const canUpgrade = enhanced.relationship_score > 75 && enhanced.current_ltv_from_partner > 5000;

      if (canUpgrade) {
        await base44.asServiceRole.entities.ReferralPartnerEnhanced.update(enhanced.id, {
          relationship_tier: 'silver'
        });

        // Send tier upgrade notification
        await base44.asServiceRole.entities.Notification.create({
          type: 'partner_tier_upgrade',
          title: `✨ ${enhanced.partner_id} upgraded to Silver Partner!`,
          message: `LTV: $${enhanced.current_ltv_from_partner}. Recommend: increased commission and co-marketing opportunities.`,
          priority: 'medium',
          recipient_role: 'admin'
        });

        result = { status: 'tier_upgraded', new_tier: 'silver' };
      } else {
        result = { status: 'not_eligible_for_upgrade', requirements: 'score > 75 and LTV > $5k' };
      }
    }

    if (action === 'commission_calculate') {
      // Calculate and track commissions
      const referral = await base44.asServiceRole.entities.Order.read(participant_id);
      const enhanced = await base44.asServiceRole.entities.ReferralPartnerEnhanced.list().then(
        data => data.find(d => d.partner_id === partner_id)
      );

      const commission_amount = (referral.total * (enhanced?.commission_rate_percent || 5)) / 100;

      // Log commission
      await base44.asServiceRole.entities.Activity.create({
        type: 'commission_earned',
        title: `Commission: ${enhanced?.partner_id}`,
        description: `Participant ${participant_id}: $${commission_amount.toFixed(2)}`,
        entity_type: 'Commission',
        entity_id: partner_id
      });

      // Update partner's total commissions
      await base44.asServiceRole.entities.ReferralPartnerEnhanced.update(enhanced.id, {
        total_commissions_paid: (enhanced?.total_commissions_paid || 0) + commission_amount
      });

      result = {
        status: 'commission_calculated',
        referral_amount: referral.total,
        commission_rate: enhanced?.commission_rate_percent,
        commission_amount
      };
    }

    return Response.json({
      status: 'action_complete',
      action,
      result
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});