import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { workflowId, triggerData } = await req.json();

    const workflow = workflowId 
      ? (await base44.entities.Workflow.filter({ id: workflowId }))[0]
      : null;

    if (!workflow) return Response.json({ error: 'Workflow not found' }, { status: 404 });
    if (workflow.status !== 'active') return Response.json({ error: 'Workflow is not active' }, { status: 400 });

    const results = [];
    const actions = workflow.actions || [];

    for (const action of actions) {
      try {
        let actionResult = null;

        switch (action.type) {
          case 'generate_insight': {
            const insight = await base44.entities.Insight.create({
              title: `Workflow Insight: ${workflow.name}`,
              description: `Automatically generated by workflow "${workflow.name}" triggered at ${new Date().toISOString()}`,
              category: 'recommendation',
              priority: 'medium',
              status: 'new'
            });
            actionResult = { success: true, created: 'insight', id: insight.id };
            break;
          }
          case 'create_notification': {
            const notif = await base44.entities.Notification.create({
              title: action.config?.title || `Workflow: ${workflow.name}`,
              message: action.config?.message || `Workflow "${workflow.name}" executed successfully`,
              type: action.config?.type || 'info',
              category: action.config?.category || 'workflow',
              status: 'unread',
              priority: 'normal'
            });
            actionResult = { success: true, created: 'notification', id: notif.id };
            break;
          }
          case 'notify_team': {
            const notif = await base44.entities.Notification.create({
              title: `Team Alert: ${workflow.name}`,
              message: action.config?.message || `Workflow "${workflow.name}" requires your attention`,
              type: 'info',
              category: 'team',
              status: 'unread',
              priority: 'high'
            });
            actionResult = { success: true, created: 'team_notification', id: notif.id };
            break;
          }
          case 'create_report': {
            const report = await base44.entities.Report.create({
              title: action.config?.title || `Auto Report: ${workflow.name}`,
              type: action.config?.type || 'analytics',
              period: action.config?.period || 'daily',
              status: 'generating'
            });
            actionResult = { success: true, created: 'report', id: report.id };
            break;
          }
          case 'auto_create_lead': {
            if (triggerData?.email) {
              const llmResult = await base44.integrations.Core.InvokeLLM({
                prompt: `Extract lead information from this email context: ${JSON.stringify(triggerData)}. Return name, email, company if detectable.`,
                response_json_schema: {
                  type: 'object',
                  properties: {
                    name: { type: 'string' },
                    email: { type: 'string' },
                    company: { type: 'string' }
                  }
                }
              });
              const client = await base44.entities.Client.create({
                name: llmResult.name || 'New Lead',
                email: llmResult.email || triggerData.email,
                company: llmResult.company || '',
                status: 'lead'
              });
              actionResult = { success: true, created: 'client', id: client.id };
            }
            break;
          }
          case 'classify_email': {
            if (triggerData?.emailId) {
              const emails = await base44.entities.Email.filter({ id: triggerData.emailId });
              if (emails[0]) {
                const classification = await base44.integrations.Core.InvokeLLM({
                  prompt: `Classify this email and generate an AI summary. Subject: "${emails[0].subject}", Body: "${emails[0].body?.substring(0, 500)}". Return priority (low/normal/high/urgent) and ai_summary.`,
                  response_json_schema: {
                    type: 'object',
                    properties: { priority: { type: 'string' }, ai_summary: { type: 'string' } }
                  }
                });
                await base44.entities.Email.update(emails[0].id, {
                  priority: classification.priority,
                  ai_summary: classification.ai_summary,
                  status: 'read'
                });
                actionResult = { success: true, updated: 'email', classification };
              }
            }
            break;
          }
          case 'track_metric': {
            const metric = await base44.entities.Metric.create({
              name: action.config?.name || 'Workflow Metric',
              value: parseFloat(action.config?.value) || 0,
              category: action.config?.category || 'efficiency',
              period: 'daily',
              unit: 'count'
            });
            actionResult = { success: true, created: 'metric', id: metric.id };
            break;
          }
          default:
            actionResult = { success: true, action: action.type, note: 'Action logged' };
        }

        results.push({ action: action.type, result: actionResult });
      } catch (err) {
        results.push({ action: action.type, error: err.message });
      }
    }

    // Update workflow run count
    await base44.entities.Workflow.update(workflow.id, {
      runs_count: (workflow.runs_count || 0) + 1,
      last_run: new Date().toISOString()
    });

    // Log activity
    await base44.entities.Activity.create({
      title: `Workflow Executed: ${workflow.name}`,
      description: `${actions.length} actions completed successfully`,
      type: 'ai_action',
      status: 'completed'
    });

    return Response.json({ success: true, workflow: workflow.name, actions_executed: results.length, results });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});