import { Link2, Loader2, Settings2, Wand2 } from "lucide-react";
import { AGENT_BY_ID } from "@/lib/agents";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function AgentProviderFabric({ agent, theme, aiProviderSettings, aiProviderDraft, setAiProviderDraft, saveAiProviderSettingsMutation, testAiProviderMutation, aiProviderMessage, updateAgentProviderOverride }) {
  if (!(agent?.id === "nexus" || agent?.id === "canvas")) return null;
  const liveConfigured = aiProviderSettings?.chat?.configured || aiProviderSettings?.image?.configured;
  const backendOffline = !aiProviderSettings;
  const setDraftField = (scope, field, value) => setAiProviderDraft((prev) => ({ ...prev, [scope]: { ...prev[scope], [field]: value } }));
  const clearDraftKey = (scope) => setAiProviderDraft((prev) => ({ ...prev, [scope]: { ...prev[scope], api_key: "", clear_api_key: true } }));
  const setSecretDraftField = (scope, value) => setAiProviderDraft((prev) => ({ ...prev, [scope]: { ...prev[scope], api_key: value, clear_api_key: false } }));
  return (
    <div className="app-soft p-4 space-y-4">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-slate-900">{agent.id === "canvas" ? "Canvas Provider Fabric" : "AI Provider Fabric"}</h3>
          <p className="text-xs text-slate-600">{agent.id === "canvas" ? "Control the live chat and image engines Canvas uses for creative generation." : "Configure the live chat and image providers your agents should use."}</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge className={liveConfigured ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}>{liveConfigured ? "live provider configured" : "fallback mode"}</Badge>
        </div>
      </div>
      {backendOffline && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
          Provider settings are visible, but the backend is not responding right now. You can still enter values here; save and test require the backend to be up.
        </div>
      )}
      <div className="grid lg:grid-cols-2 gap-4">
        <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-semibold text-slate-900">Chat Intelligence</h4>
            <Badge className={aiProviderSettings?.chat?.configured ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}>{aiProviderSettings?.chat?.configured ? (aiProviderSettings?.chat?.api_key_masked || "configured") : "fallback"}</Badge>
          </div>
          <select className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" value={aiProviderDraft.chat.provider} onChange={(e) => setDraftField("chat", "provider", e.target.value)}>
            <option value="fallback">Fallback only</option><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="ollama">Ollama</option>
          </select>
          <input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Chat model" value={aiProviderDraft.chat.model} onChange={(e) => setDraftField("chat", "model", e.target.value)} />
          {(aiProviderDraft.chat.provider === "gemini" || aiProviderDraft.chat.provider === "openai" || aiProviderDraft.chat.provider === "ollama") && <div className="grid gap-2 md:grid-cols-3"><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Lite model" value={aiProviderDraft.chat.model_lite || ""} onChange={(e) => setDraftField("chat", "model_lite", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Standard model" value={aiProviderDraft.chat.model_standard || ""} onChange={(e) => setDraftField("chat", "model_standard", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Premium model" value={aiProviderDraft.chat.model_premium || ""} onChange={(e) => setDraftField("chat", "model_premium", e.target.value)} /></div>}
          <input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Base URL" value={aiProviderDraft.chat.base_url} onChange={(e) => setDraftField("chat", "base_url", e.target.value)} />
          <input type="password" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder={aiProviderDraft.chat?.api_key_present ? "Enter new API key to replace current secret" : "API key"} value={aiProviderDraft.chat.api_key} onChange={(e) => setSecretDraftField("chat", e.target.value)} />
          <div className="flex items-center justify-between gap-2 text-[11px] text-slate-500">
            <span>{aiProviderDraft.chat?.api_key_present ? `Stored secret: ${aiProviderDraft.chat?.api_key_masked || "configured"}` : "No chat API key stored"}</span>
            {aiProviderDraft.chat?.api_key_present && <Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => clearDraftKey("chat")}>Clear Key</Button>}
          </div>
          {(aiProviderDraft.chat.provider === "gemini" || aiProviderDraft.chat.provider === "openai" || aiProviderDraft.chat.provider === "ollama") && <p className="text-[11px] text-slate-500">The router will choose between lite, standard, and premium models per turn based on risk, ambiguity, and reasoning depth.</p>}
          <div className="flex flex-wrap gap-2">
            <Button size="sm" className={`rounded-lg ${theme.button} text-white`} onClick={() => saveAiProviderSettingsMutation.mutate()} disabled={saveAiProviderSettingsMutation.isPending}>{saveAiProviderSettingsMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Settings2 className="w-3 h-3 mr-2" />}Save</Button>
            <Button size="sm" variant="outline" className="rounded-lg" onClick={() => testAiProviderMutation.mutate({ kind: "chat", agentId: agent.id === "canvas" ? "canvas" : "" })} disabled={testAiProviderMutation.isPending}>{testAiProviderMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Link2 className="w-3 h-3 mr-2" />}Test Chat</Button>
          </div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-3">
          <div className="flex items-center justify-between"><h4 className="text-sm font-semibold text-slate-900">Image Generation</h4><Badge className={aiProviderSettings?.image?.configured ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}>{aiProviderSettings?.image?.configured ? (aiProviderSettings?.image?.api_key_masked || "configured") : "fallback"}</Badge></div>
          <select className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" value={aiProviderDraft.image.provider} onChange={(e) => setDraftField("image", "provider", e.target.value)}><option value="fallback">Fallback only</option><option value="openai">OpenAI</option><option value="pollinations">Pollinations</option><option value="automatic1111">Automatic1111</option></select>
          <input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Image model" value={aiProviderDraft.image.model} onChange={(e) => setDraftField("image", "model", e.target.value)} />
          <input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Base URL" value={aiProviderDraft.image.base_url} onChange={(e) => setDraftField("image", "base_url", e.target.value)} />
          <div className="grid grid-cols-2 gap-2"><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Size" value={aiProviderDraft.image.size} onChange={(e) => setDraftField("image", "size", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Quality" value={aiProviderDraft.image.quality} onChange={(e) => setDraftField("image", "quality", e.target.value)} /></div>
          <input type="password" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder={aiProviderDraft.image?.api_key_present ? "Enter new API key to replace current secret" : "API key"} value={aiProviderDraft.image.api_key} onChange={(e) => setSecretDraftField("image", e.target.value)} />
          <div className="flex items-center justify-between gap-2 text-[11px] text-slate-500">
            <span>{aiProviderDraft.image?.api_key_present ? `Stored secret: ${aiProviderDraft.image?.api_key_masked || "configured"}` : "No image API key stored"}</span>
            {aiProviderDraft.image?.api_key_present && <Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => clearDraftKey("image")}>Clear Key</Button>}
          </div>
          <div className="flex flex-wrap gap-2"><Button size="sm" className={`rounded-lg ${theme.button} text-white`} onClick={() => saveAiProviderSettingsMutation.mutate()} disabled={saveAiProviderSettingsMutation.isPending}>{saveAiProviderSettingsMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Settings2 className="w-3 h-3 mr-2" />}Save</Button><Button size="sm" variant="outline" className="rounded-lg" onClick={() => testAiProviderMutation.mutate({ kind: "image", agentId: agent.id === "canvas" ? "canvas" : "" })} disabled={testAiProviderMutation.isPending}>{testAiProviderMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Wand2 className="w-3 h-3 mr-2" />}Test Image</Button></div>
        </div>
      </div>
      <div className="grid lg:grid-cols-2 gap-4">
        <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-3"><div className="flex items-center justify-between"><h4 className="text-sm font-semibold text-slate-900">Voice Generation</h4><Badge className={aiProviderSettings?.voice?.configured ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}>{aiProviderSettings?.voice?.configured ? (aiProviderSettings?.voice?.api_key_masked || aiProviderSettings?.voice?.provider || "configured") : "fallback"}</Badge></div><select className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" value={aiProviderDraft.voice.provider} onChange={(e) => setDraftField("voice", "provider", e.target.value)}><option value="fallback">Fallback only</option><option value="openai">OpenAI</option></select><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Voice model" value={aiProviderDraft.voice.model} onChange={(e) => setDraftField("voice", "model", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Voice preset" value={aiProviderDraft.voice.voice} onChange={(e) => setDraftField("voice", "voice", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Base URL" value={aiProviderDraft.voice.base_url} onChange={(e) => setDraftField("voice", "base_url", e.target.value)} /><input type="password" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder={aiProviderDraft.voice?.api_key_present ? "Enter new API key to replace current secret" : "API key"} value={aiProviderDraft.voice.api_key} onChange={(e) => setSecretDraftField("voice", e.target.value)} /><div className="flex items-center justify-between gap-2 text-[11px] text-slate-500"><span>{aiProviderDraft.voice?.api_key_present ? `Stored secret: ${aiProviderDraft.voice?.api_key_masked || "configured"}` : "No voice API key stored"}</span>{aiProviderDraft.voice?.api_key_present && <Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => clearDraftKey("voice")}>Clear Key</Button>}</div><div className="flex flex-wrap gap-2"><Button size="sm" className={`rounded-lg ${theme.button} text-white`} onClick={() => saveAiProviderSettingsMutation.mutate()} disabled={saveAiProviderSettingsMutation.isPending}>{saveAiProviderSettingsMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Settings2 className="w-3 h-3 mr-2" />}Save</Button><Button size="sm" variant="outline" className="rounded-lg" onClick={() => testAiProviderMutation.mutate({ kind: "voice", agentId: agent.id === "canvas" ? "canvas" : "" })} disabled={testAiProviderMutation.isPending}>{testAiProviderMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Wand2 className="w-3 h-3 mr-2" />}Test Voice</Button></div></div>
        <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-3"><div className="flex items-center justify-between"><h4 className="text-sm font-semibold text-slate-900">Video Generation</h4><Badge className={aiProviderSettings?.video?.configured ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}>{aiProviderSettings?.video?.configured ? (aiProviderSettings?.video?.api_key_masked || aiProviderSettings?.video?.provider || "configured") : "fallback"}</Badge></div><select className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" value={aiProviderDraft.video.provider} onChange={(e) => setDraftField("video", "provider", e.target.value)}><option value="fallback">Fallback only</option><option value="openai">OpenAI</option></select><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Video model" value={aiProviderDraft.video.model} onChange={(e) => setDraftField("video", "model", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Base URL" value={aiProviderDraft.video.base_url} onChange={(e) => setDraftField("video", "base_url", e.target.value)} /><input className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder="Quality" value={aiProviderDraft.video.quality} onChange={(e) => setDraftField("video", "quality", e.target.value)} /><input type="password" className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white" placeholder={aiProviderDraft.video?.api_key_present ? "Enter new API key to replace current secret" : "API key"} value={aiProviderDraft.video.api_key} onChange={(e) => setSecretDraftField("video", e.target.value)} /><div className="flex items-center justify-between gap-2 text-[11px] text-slate-500"><span>{aiProviderDraft.video?.api_key_present ? `Stored secret: ${aiProviderDraft.video?.api_key_masked || "configured"}` : "No video API key stored"}</span>{aiProviderDraft.video?.api_key_present && <Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => clearDraftKey("video")}>Clear Key</Button>}</div><div className="flex flex-wrap gap-2"><Button size="sm" className={`rounded-lg ${theme.button} text-white`} onClick={() => saveAiProviderSettingsMutation.mutate()} disabled={saveAiProviderSettingsMutation.isPending}>{saveAiProviderSettingsMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Settings2 className="w-3 h-3 mr-2" />}Save</Button><Button size="sm" variant="outline" className="rounded-lg" onClick={() => testAiProviderMutation.mutate({ kind: "video", agentId: agent.id === "canvas" ? "canvas" : "" })} disabled={testAiProviderMutation.isPending}>{testAiProviderMutation.isPending ? <Loader2 className="w-3 h-3 mr-2 animate-spin" /> : <Wand2 className="w-3 h-3 mr-2" />}Test Video</Button></div></div>
      </div>
      <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">{aiProviderMessage || "Use Gemini for stronger chat reasoning, Ollama for local chat, or Pollinations/Automatic1111/OpenAI for image generation."}</div>
      {agent.id === "nexus" && <div className="rounded-xl border border-slate-200 bg-white p-4 space-y-3"><div><h4 className="text-sm font-semibold text-slate-900">Per-Agent Provider Overrides</h4><p className="text-xs text-slate-600">Choose which chat and image provider each agent should prefer when an override is needed.</p></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{Object.keys(AGENT_BY_ID).map((agentKey) => { const override = aiProviderDraft.agent_overrides?.[agentKey] || {}; return <div key={`provider-override-${agentKey}`} className="rounded-lg border border-slate-200 bg-slate-50 p-3 space-y-2"><p className="text-xs font-semibold text-slate-900">{AGENT_BY_ID[agentKey]?.name || agentKey}</p><select className="w-full border border-slate-300 rounded-lg px-2 py-1.5 text-xs bg-white" value={override.chat?.provider || ""} onChange={(e) => updateAgentProviderOverride(agentKey, "chat", "provider", e.target.value)}><option value="">Use global chat</option><option value="fallback">Fallback</option><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="ollama">Ollama</option></select><select className="w-full border border-slate-300 rounded-lg px-2 py-1.5 text-xs bg-white" value={override.image?.provider || ""} onChange={(e) => updateAgentProviderOverride(agentKey, "image", "provider", e.target.value)}><option value="">Use global image</option><option value="fallback">Fallback</option><option value="pollinations">Pollinations</option><option value="automatic1111">Automatic1111</option><option value="openai">OpenAI</option></select><div className="flex gap-2"><Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => testAiProviderMutation.mutate({ kind: "chat", agentId: agentKey })} disabled={testAiProviderMutation.isPending}>Test Chat</Button><Button size="sm" variant="outline" className="rounded h-7 text-[10px] px-2" onClick={() => testAiProviderMutation.mutate({ kind: "image", agentId: agentKey })} disabled={testAiProviderMutation.isPending}>Test Image</Button></div></div>; })}</div></div>}
    </div>
  );
}

